safety_bonds:
    fc_comms_msp:
        priority: 50
    low_level_motion:
        priority: 200
    motion_planner:
        priority: 250
    takeoff_land_abstract:
        priority: 1000
    motors_test:
        priority: 1000
    takeoff_translate_land_abstract:
        priority: 1000
    track_roomba_abstract:
        priority: 1000
    hold_position_abstract:
        priority: 1000
