safety_bonds:
    absolute_switch_velocity_publisher:
        priority: 40
    fc_comms_msp:
        priority: 50
    long_range_altimeter:
        priority: 60
    orientation_filter:
        priority: 100
    low_level_motion:
        priority: 200
    motion_planner:
        priority: 250
    takeoff_land_abstract:
        priority: 1000
    motors_test:
        priority: 1000
    takeoff_translate_land_abstract:
        priority: 1000
    track_roomba_abstract:
        priority: 1000
    hold_position_abstract:
        priority: 1000
    hit_roomba_abstract:
        priority: 1000
    velocity_test_abstract:
        priority: 1000
    block_roomba_abstract: 
        priority: 1000
